[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@exercises/=src/exercises/"]
via_ir = true

[fmt]
line_length = 80

[profile.solution]
remappings = ["@exercises/=src/solutions/"]
